services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.28
    container_name: openhands-app
    pull_policy: always
    tty: true
    stdin_open: true
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.28-nikolaik
      - LOG_ALL_EVENTS=true
      - SANDBOX_USER_ID=0
      - WORKSPACE_BASE=/mnt/e/htdocs/Nyx-OpenHands
      - WORKSPACE_MOUNT_PATH=/mnt/e/htdocs/Nyx-OpenHands
      - WORKSPACE_MOUNT_PATH_IN_SANDBOX=/workspace
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.openhands-state:/.openhands-state:rw
      - /mnt/e/htdocs/Nyx-OpenHands:/opt/workspace_base:rw
    networks:
      - openhands-net
    
  ollama:
    build:
      context: ./
      dockerfile: ./containers/ollama/Dockerfile
    container_name: openhands-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - openhands-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:11434/api/generate", "-d", "{\"model\":\"${OLLAMA_MODEL}\",\"prompt\":\"test\",\"stream\":false}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

networks:
  openhands-net:
    name: openhands-net
    driver: bridge

volumes:
  ollama_data:
    name: openhands_ollama_data
